apiVersion: v1
kind: Secret
metadata:
  name: tenantflow-db-credentials
  namespace: default
  labels:
    app: tenantflow
type: Opaque
stringData:
  # MongoDB Atlas API Credentials
  ATLAS_PUBLIC_KEY: "adcjpbcz"
  ATLAS_PRIVATE_KEY: "0a4d5219-65a9-4a87-b58e-5f679fbc696e"
  ATLAS_PROJECT_ID: "5fc94a76de2da00102cc7c07"
  ATLAS_CLUSTER_NAME: "educationelly-db"
  ATLAS_CLUSTER_URL: "educationelly-db.92qr2ay.mongodb.net"

  # Test Database (MongoDB)
  TEST_DB_CONNECTION_STRING: "mongodb+srv://username:password@cluster.mongodb.net/test"
  TEST_DB_USERNAME: "username"
  TEST_DB_PASSWORD: "password"

  # Educationelly Database (MongoDB Atlas)
  EDUCATIONELLY_DB_CONNECTION_STRING: "mongodb+srv://username:password@educationelly-db.92qr2ay.mongodb.net/educationelly-db"
  EDUCATIONELLY_DB_USERNAME: "username"
  EDUCATIONELLY_DB_PASSWORD: "password"

  # Spaced Repetition Database (MongoDB Atlas)
  SPACED_REPETITION_CONNECTION_STRING: "mongodb+srv://username:password@spaced-repetition.juv8wvf.mongodb.net/spaced-repetition"
  SPACED_REPETITION_USERNAME: "username"
  SPACED_REPETITION_PASSWORD: "password"

  # PostgreSQL AWS RDS
  POSTGRES_AWS_CONNECTION_STRING: "postgres://ue2p717tmbg7uj:p5181fcc48b09e9c27b27fe64c388e33f675c42effa900b05979b61857159925d@c5cnr847jq0fj3.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com:5432/de3iq68tg4peu"
  POSTGRES_AWS_USERNAME: "ue2p717tmbg7uj"
  POSTGRES_AWS_PASSWORD: "p5181fcc48b09e9c27b27fe64c388e33f675c42effa900b05979b61857159925d"

  # Neon PostgreSQL
  NEONDB_CONNECTION_STRING: "postgres://neondb_owner:npg_GeqU0vP03TaF@ep-flat-resonance-addiekdb-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require"
  NEONDB_USERNAME: "neondb_owner"
  NEONDB_PASSWORD: "npg_GeqU0vP03TaF"
