---
# Service Account for the multi-tenant platform control plane
apiVersion: v1
kind: ServiceAccount
metadata:
  name: multi-tenant-controller
  namespace: default
---
# ClusterRole for managing tenant namespaces
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: multi-tenant-controller
rules:
  # Namespace management
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "create", "delete", "watch"]

  # Resource quota management
  - apiGroups: [""]
    resources: ["resourcequotas"]
    verbs: ["get", "list", "create", "update", "delete"]

  # Pod, Service, Deployment management within namespaces
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps", "secrets"]
    verbs: ["get", "list", "create", "update", "delete", "watch"]

  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets", "statefulsets"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]

  # Network policies
  - apiGroups: ["networking.k8s.io"]
    resources: ["networkpolicies"]
    verbs: ["get", "list", "create", "update", "delete"]

  # Persistent volumes for databases
  - apiGroups: [""]
    resources: ["persistentvolumeclaims", "persistentvolumes"]
    verbs: ["get", "list", "create", "update", "delete"]
---
# ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: multi-tenant-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: multi-tenant-controller
subjects:
  - kind: ServiceAccount
    name: multi-tenant-controller
    namespace: default
---
# Role for tenant-specific access (example for a single tenant)
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tenant-admin
  namespace: TENANT_NAMESPACE
rules:
  - apiGroups: ["", "apps", "networking.k8s.io"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]

  # Allow scaling deployments
  - apiGroups: ["apps"]
    resources: ["deployments/scale"]
    verbs: ["get", "update", "patch"]
---
# RoleBinding for tenant access
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tenant-admin-binding
  namespace: TENANT_NAMESPACE
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tenant-admin
subjects:
  - kind: ServiceAccount
    name: TENANT_SERVICE_ACCOUNT
    namespace: TENANT_NAMESPACE
